// Program.cs is the composition root of the application.
// In Clean Architecture, this is where we wire up dependency injection,
// middleware, and the HTTP pipeline. It must not contain business logic.

var builder = WebApplication.CreateBuilder(args);

// --- Service registration (DI container) ---
// Each layer exposes an extension method on IServiceCollection
// so that Program.cs stays thin and each layer owns its own registration.
// These extension methods will be added in their respective tickets.

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// --- HTTP request pipeline ---
// Middleware order matters. This is the minimal, correct order for a Web API.
// More middleware (exception handling, authentication, authorization, etc.)
// will be added in later tickets, in the correct positions.

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c=>{
        // Points Swagger UI to the endpoint generated by Swashbuckle
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1");}

    );
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();